---
stages:
  - prepare
  - build
  - release

prepare:stable:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull dockerwest/nginx:stable
  only:
    - main

prepare:mainline:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull dockerwest/nginx:mainline
  only:
    - main

build:stable:
  stage: build
  tags:
    - dockerwest
  script:
    - cd stable; ./build.sh
  only:
    - main

build:mainline:
  stage: build
  tags:
    - dockerwest
  script:
    - cd mainline; ./build.sh
  only:
    - main

release:stable:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/nginx-pimcore10:stable
  only:
    - main

release:mainline:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/nginx-pimcore10:mainline
  only:
    - main
